# Generated by Django 2.1.1 on 2018-10-16 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0042_auto_20181006_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='media',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='primeiraUnidade',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='segundaUnidade',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='terceiraUnidade',
        ),
    ]
