# Generated by Django 2.1.2 on 2018-10-16 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0043_auto_20181015_2341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividadesprofessor',
            name='perguntas',
        ),
        migrations.RemoveField(
            model_name='atividadesprofessor',
            name='professor',
        ),
        migrations.AddField(
            model_name='perguntasx',
            name='matricula_professor',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='perguntasx',
            name='titulo',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='professor',
            name='matricula',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='professor',
            name='nomeInstituicao',
            field=models.CharField(max_length=30),
        ),
        migrations.DeleteModel(
            name='AtividadesProfessor',
        ),
    ]
