# Generated by Django 2.1.2 on 2018-10-16 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0044_auto_20181016_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perguntasx',
            name='matricula_professor',
            field=models.CharField(max_length=100),
        ),
    ]
